// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaHorarios.Infrastructura;

#nullable disable

namespace SistemaHorarios.Infrastructura.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240523214912_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.29");

            modelBuilder.Entity("SistemaHorarios.Dominio.Grupos.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Grado", "Nombre");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.Horarios.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId")
                        .IsUnique();

                    b.ToTable("horarios", (string)null);
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.Horarios.HorarioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaestroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MateriaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HoraId");

                    b.HasIndex("HorarioId");

                    b.HasIndex("MaestroId");

                    b.HasIndex("MateriaId");

                    b.ToTable("HorarioItems", (string)null);
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.Maestros.Maestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("maestros", (string)null);
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.MayasCurriculares.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MayaCurricularId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("MayaCurricularId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("materias", (string)null);
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.MayasCurriculares.MayaCurricular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("mayas_curriculares", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grado = 1
                        },
                        new
                        {
                            Id = 2,
                            Grado = 2
                        },
                        new
                        {
                            Id = 3,
                            Grado = 3
                        });
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.Shared.Hora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsReceso")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("Fin")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Inicio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Horas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsReceso = false,
                            Fin = new TimeOnly(8, 0, 0),
                            Inicio = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EsReceso = false,
                            Fin = new TimeOnly(9, 0, 0),
                            Inicio = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EsReceso = false,
                            Fin = new TimeOnly(10, 0, 0),
                            Inicio = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EsReceso = true,
                            Fin = new TimeOnly(10, 20, 0),
                            Inicio = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            EsReceso = false,
                            Fin = new TimeOnly(11, 10, 0),
                            Inicio = new TimeOnly(10, 20, 0)
                        },
                        new
                        {
                            Id = 6,
                            EsReceso = false,
                            Fin = new TimeOnly(12, 0, 0),
                            Inicio = new TimeOnly(11, 10, 0)
                        },
                        new
                        {
                            Id = 7,
                            EsReceso = true,
                            Fin = new TimeOnly(12, 20, 0),
                            Inicio = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            EsReceso = false,
                            Fin = new TimeOnly(1, 10, 0),
                            Inicio = new TimeOnly(12, 20, 0)
                        },
                        new
                        {
                            Id = 9,
                            EsReceso = false,
                            Fin = new TimeOnly(2, 10, 0),
                            Inicio = new TimeOnly(1, 10, 0)
                        });
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.Horarios.Horario", b =>
                {
                    b.HasOne("SistemaHorarios.Dominio.Grupos.Grupo", "Grupo")
                        .WithOne("Horario")
                        .HasForeignKey("SistemaHorarios.Dominio.Horarios.Horario", "GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.Horarios.HorarioItem", b =>
                {
                    b.HasOne("SistemaHorarios.Dominio.Shared.Hora", "Hora")
                        .WithMany()
                        .HasForeignKey("HoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Dominio.Horarios.Horario", null)
                        .WithMany("Items")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Dominio.Maestros.Maestro", "Maestro")
                        .WithMany()
                        .HasForeignKey("MaestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaHorarios.Dominio.MayasCurriculares.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hora");

                    b.Navigation("Maestro");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.MayasCurriculares.Materia", b =>
                {
                    b.HasOne("SistemaHorarios.Dominio.MayasCurriculares.MayaCurricular", null)
                        .WithMany("Materias")
                        .HasForeignKey("MayaCurricularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.Grupos.Grupo", b =>
                {
                    b.Navigation("Horario");
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.Horarios.Horario", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SistemaHorarios.Dominio.MayasCurriculares.MayaCurricular", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
